version: "3"
services:
  crossbar:
    image: crossbario/crossbar
    volumes:
      - .:/node
    ports:
      - "80:8080"
    networks:
      - webnet
  db:
    image: couchbase
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    volumes:
      - ./couchbase:/opt/couchbase/var
    networks:
      - webnet
  server:
    depends_on:
      - db
      - crossbar
    image: "node:9"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/home/node/app
    expose:
      - "8081"
    command: "npm start"
    networks:
      - webnet
networks:
  webnet: